services:
  - type: web
    name: pinet-check
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: 'composer install'
    startCommand: 'apache2-foreground'
    autoDeploy: true
